### PR TITLE
Explicit count modifiers

### LINKED ISSUE #142: String-related highlighting error
The highlighting in https://github.com/twbs/bootlint/blob/9f9ac92ea1288fb1af5f281d924aa3abd1c7770f/src/bootlint.js#L603 goes wrong starting on line 604.
(GitHub is currently using v0.72 of this project for its JS syntax highlighting; see https://github.com/github/linguist/tree/master/vendor/grammars )

### PR DESCRIPTION
**Pull request by pchaigno**
The construction `{,2}` in regular expressions is only supported by Oniguruma (which is used by Atom). This Atom bundle is used to highlight JavaScript code on GitHub. However, GitHub is using a [PCRE-based engine](https://github.com/vmg/pcre) for regexes and thus, the following code gets incorrectly highlighted.
```javascript
addLinter("E014", function lintColParentsAreRowsOrFormGroups($, reporter) {
        var selector = COL_CLASSES.map(function (colClass) {
            return '*:not(.row):not(.form-group)>' + colClass + ':not(col):not(th):not(td)';
        }).join(',');
        var colsOutsideRowsAndFormGroups = $(selector);
        if (colsOutsideRowsAndFormGroups.length) {
            reporter("Columns (`.col-*-*`) can only be children of `.row`s or `.form-group`s", colsOutsideRowsAndFormGroups);
        }
    });
```

This pull request fixes that by using an explicit count modifier in the regex.
Fixes #142.

### CODE REVIEW

**Comment by mnquintana** [comment]
I feel like we should add specs for this, but it sounds like this may be untestable since the bug wasn't in Atom. Hmm.

**Comment by pchaigno** [comment]
> I feel like we should add specs for this

I agree. Would it be possible to just check that the grammar doesn't contain `{,`? It's not as neat but it might be better than nothing...

**Comment by mnquintana** [comment]
@pchaigno Yeah, I think that would be better than nothing. Go for it!

**Comment by pchaigno** [comment]
@mnquintana I'll do that tonight, and also check that it does fix #142 (not the first time I see this issue so I'm pretty sure that's the cause).

**Comment by pchaigno** [comment]
I added a test for this. It's my first lines in CoffeeScript so I'm not sure it respects the conventions and styleguide...
Should I move the require to the beginning of the file?

**Comment by pchaigno** [comment]
And it does fix the issue: [example in Lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fpchaigno%2Flanguage-javascript%2Fexplicit-count-modifiers%2Fgrammars%2Fjavascript.cson&grammar_text=&code_source=from-text&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Ftwbs%2Fbootlint%2F9f9ac92ea1288fb1af5f281d924aa3abd1c7770f%2Fsrc%2Fbootlint.js&code=addLinter%28%22E014%22%2C+function+lintColParentsAreRowsOrFormGroups%28%24%2C+reporter%29+{%0D%0A++++++++var+selector+%3D+COL_CLASSES.map%28function+%28colClass%29+{%0D%0A++++++++++++return+%27*%3Anot%28.row%29%3Anot%28.form-group%29%3E%27+%2B+colClass+%2B+%27%3Anot%28col%29%3Anot%28th%29%3Anot%28td%29%27%3B%0D%0A++++++++}%29.join%28%27%2C%27%29%3B%0D%0A++++++++var+colsOutsideRowsAndFormGroups+%3D+%24%28selector%29%3B%0D%0A++++++++if+%28colsOutsideRowsAndFormGroups.length%29+{%0D%0A++++++++++++reporter%28%22Columns+%28%60.col-*-*%60%29+can+only+be+children+of+%60.row%60s+or+%60.form-group%60s%22%2C+colsOutsideRowsAndFormGroups%29%3B%0D%0A++++++++}%0D%0A++++}%29%3B).

File: spec/javascript-spec.coffee [hunk 1]
```diff
@@ -85,6 +85,13 @@ describe "Javascript grammar", ->
       {tokens} = grammar.tokenizeLine('0O1411')
       expect(tokens[0]).toEqual value: '0O1411', scopes: ['source.js', 'constant.numeric.js']
 
+    it "regular expressions have explicit count modifiers", ->
```
Comment (50Wliu) [inline spec/javascript-spec.coffee]: Specs should flow with the `it`, eg `it "tokenizes regular expressions that have explicit count modifiers"`
This obviously doesn't work here since it's not testing tokenization but it's an example.

Comment (pchaigno) [inline spec/javascript-spec.coffee]: Oops, thanks for the review.
Do you have better than `"verifies that regular expressions have explicit count modifiers"`?

Comment (kevinsawicki) [inline spec/javascript-spec.coffee]: `includes explicit count modifiers in all patterns` sounds good to me

Comment (pchaigno) [inline spec/javascript-spec.coffee]: That makes sense. I couldn't understand what `it` referred to.
Thanks @kevinsawicki!

**Comment by kevinsawicki** [comment]
Great, thanks for this :ship:
